name: Run Roboshop shell script
on: workflow_dispatch
jobs:
  frontend:
    runs-on: self-hosted
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "frontend.maksuduldevsecops.online" > /tmp/host

      - name: Run frontend remotely
        env: { HOST: frontend.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash frontend.sh
          "'

  mongodb:
    runs-on: self-hosted
    needs: [frontend]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "mongodb.maksuduldevsecops.online" > /tmp/host

      - name: Run mongodb remotely
        env: { HOST: mongodb.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash mongodb.sh
          "'

  catalogue:
    runs-on: self-hosted
    needs: [ mongodb ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "catalogue.maksuduldevsecops.online" > /tmp/host

      - name: Run catalogue remotely
        env: { HOST: catalogue.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash catalogue.sh
          "'

  redis:
    runs-on: self-hosted
    needs: [ catalogue ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "redis.maksuduldevsecops.online" > /tmp/host

      - name: Run redis remotely
        env: { HOST: redis.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash redis.sh
          "'

  user:
    runs-on: self-hosted
    needs: [ redis ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "user.maksuduldevsecops.online" > /tmp/host

      - name: Run user remotely
        env: { HOST: user.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash user.sh
          "'

  cart:
    runs-on: self-hosted
    needs: [ user ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "cart.maksuduldevsecops.online" > /tmp/host

      - name: Run cart remotely
        env: { HOST: cart.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash cart.sh
          "'

  mysql:
    runs-on: self-hosted
    needs: [ cart ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "mysql.maksuduldevsecops.online" > /tmp/host

      - name: Run mysql remotely
        env: { HOST: mysql.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash mysql.sh
          "'

  shipping:
    runs-on: self-hosted
    needs: [ mysql ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "shipping.maksuduldevsecops.online" > /tmp/host

      - name: Run shipping remotely
        env: { HOST: shipping.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash shipping.sh
          "'

  rabbitmq:
    runs-on: self-hosted
    needs: [ shipping ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "rabbitmq.maksuduldevsecops.online" > /tmp/host

      - name: Run rabbitmq remotely
        env: { HOST: rabbitmq.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash rabbitmq.sh
          "'

  payment:
    runs-on: self-hosted
    needs: [ rabbitmq ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "payment.maksuduldevsecops.online" > /tmp/host

      - name: Run payment remotely
        env: { HOST: payment.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash payment.sh
          "'

  dispatch:
    runs-on: self-hosted
    needs: [ payment ]
    steps:
      - name: Add SSH key
        run: |
          install -m 600 /dev/stdin ~/.ssh/id_rsa <<< "${{ secrets.SSH_KEY }}"
          printf "%s\n" "dispatch.maksuduldevsecops.online" > /tmp/host

      - name: Run dispatch remotely
        env: { HOST: dispatch.maksuduldevsecops.online }
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST 'bash -lc "
            set -e
            if [ -d Maksudul-s-DevOps-Stuffs ]; then
              cd Maksudul-s-DevOps-Stuffs && git pull --rebase
            else
              git clone https://github.com/aminrana37/Maksudul-s-DevOps-Stuffs.git
              cd Maksudul-s-DevOps-Stuffs
            fi
            cd roboshop-shell
            ls -la                # optional
            sudo bash dispatch.sh
          "'  





