name: Run Roboshop ansible playbooks
on: workflow_dispatch
jobs:
  frontend:
    runs-on: self-hosted
    steps:
      - name: Run ansible script for frontend
        run: make frontend component=frontend
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible

  redis:
    runs-on: self-hosted
    needs: [ frontend ]
    steps:
      - name: Running ansible script for redis
        run: make redis component=redis
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible

  mongodb:
    runs-on: self-hosted
    needs: [ redis ]
    steps:
      - name: Running ansible script for mongodb
        run: make mongodb component=mongodb
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible

  mysql:
    runs-on: self-hosted
    needs: [ mongodb ]
    steps:
      - name: Running ansible script for mysql
        run: make mysql component=mysql
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible

  rabbitmq:
    runs-on: self-hosted
    needs: [ mysql ]
    steps:
      - name: Running ansible script for rabbitmq
        run: make rabbitmq component=rabbitmq
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible


  catalogue:
    runs-on: self-hosted
    needs: [ rabbitmq ]
    steps:
      - name: Running ansible script for catalogue
        run: make catalogue component=catalogue
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible


  user:
    runs-on: self-hosted
    needs: [ catalogue ]
    steps:
      - name: Running script for user
        run: make user component=user
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible


  cart:
    runs-on: self-hosted
    needs: [ user ]
    steps:
      - name: Running ansible script for cart
        run: make cart component=cart
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible


  shipping:
    runs-on: self-hosted
    needs: [ cart ]
    steps:
      - name: Running ansible script for shipping
        run: make shipping component=shipping
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible


  payment:
    runs-on: self-hosted
    needs: [ shipping ]
    steps:
      - name: Running ansible script for payment
        run: make payment component=payment
        working-directory: /home/ec2-user/Maksudul-s-DevOps-Stuffs/roboshop-ansible



